version: 2

sources:
  - name: airbnb # A logical name for the source system 
    schema: raw # The physical schema name in your database

    tables:
      - name: listings # The physical table name
        identifier: raw_listings # Optional: specify the identifier if it differs from the table name
        # Optional: add a description for documentation
        description: >
          Raw listings data from the Airbnb application.
      
      - name: reviews
        identifier: raw_reviews
        description: Raw reviews data from the Airbnb application.

      - name: hosts
        identifier: raw_hosts
        description: Raw hosts data from the Airbnb application.